### ISSUE TITLE
Article template: Ability to embed a video

### ISSUE THREAD

**Issue by calexity** [cal-itp/mobility-marketplace#193]
As the content team,
When I am writing an article
I want to be able to embed a video from Youtube
So that I can share talks or presentation our team has made within an article

---

This story includes

- Ability to embed a YouTube video

**Resources**
- [Design in Figma ](https://www.figma.com/file/QR2c1HOhrJptQbN0FSfu9J/Mobility-Marketplace?node-id=2311%3A9328)(see Design 1.2 Release)

**QA**
- Kurtis will get to PR, which will include a deploy preview link
- @calexity will assist Harrison and Jess in accepting the completed story

**Comment by thekaveman** [comment]
Just FYI, we created a component for Youtube video embeds here: https://github.com/cal-itp/transit-stop/blob/dev/admin/editor/youtube.js

It is registered for use in the CMS here: https://github.com/cal-itp/transit-stop/blob/dev/admin/editor/index.js

And added to (for now, only one) content type here: https://github.com/cal-itp/transit-stop/blob/dev/admin/config.yml#L272

(that is for the Confirmation message on the Subscribe page). Easy to add it to other types by following a similar config. 

It doesn't support Vimeo though, so either the component needs to be modified or a new one created.

**Comment by calexity** [comment]
Great @thekaveman! Thank you. I don't think Vimeo is necessary. YouTube should get us started.

Is there any work at all left to pull this into an article/to make it available to the content team for use then?

**Comment by thekaveman** [comment]
The `posts` type needs to be defined in [admin/config.yml](https://github.com/cal-itp/transit-stop/blob/dev/admin/config.yml) (looks like it was removed as part of the [removal of search](https://github.com/cal-itp/transit-stop/commit/c8ee52cb9b86d3795946ea00b52883705daa7900#diff-9abfe3affac6a024a46cffd5d45a8243ed686f7431a0509353f26b4278ca65dfL348)).

You can see the definition should have most of what is needed (including Author stuff for #192), assuming the design hasn't changed drastically. The one area that probably has changed is in the use of "category", which we previously conceived of as a separate content type/landing page. 

Here it is again:

```yml
- name: "posts"
  label: "Articles"
  label_singular: "Article"
  description: "Short and long-form content with a publish date and author."
  folder: "content/_posts"
  sort: "date:desc"
  create: true
  editor:
    preview: false
  preview_path: "/blog/{{year}}/{{month}}/{{slug}}"
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  fields:
    - {
        label: "Publish date",
        name: "date",
        widget: "datetime",
        hint: "Publish date is captured in UTC but displays in Pacific",
        date_format: "LL",
        time_format: false,
        picker_utc: true
      }
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Subtitle", name: "subtitle", widet: "string", required: false}
    - {
        label: "Author",
        name: "author",
        widget: "relation",
        collection: "metadata",
        file: "authors",
        search_fields: ["items.*.first_name", "items.*.last_name"],
        display_fields: ["items.*.first_name", "items.*.last_name"],
        value_field: "items.*.ref_id"
      }
    - {
        label: "Category",
        name: "category",
        widget: "relation",
        collection: "categories",
        value_field: "ref_id",
        search_fields: ["title", "text", "body"],
        display_fields: ["title"]
      }
    - {label: "Summary", name: "description", widget: "string", hint: "Used for card, Social Media, and other summary displays"}
    - {
        label: "Body",
        name: "body",
        widget: "markdown",
        buttons: [
          bold,
          italic,
          link,
          heading-two,
          heading-three,
          heading-four,
          heading-five,
          heading-six,
          bulleted-list,
          numbered-list
        ],
        editor_components: [
          "image",
          "image-caption",
          "pull-quote",
          "youtube"
        ]
      }
    - {
        label: "Call to Action",
        name: "action",
        required: false,
        widget: "relation",
        collection: "actions",
        value_field: "ref_id",
        search_fields: ["title", "text", "body"],
        display_fields: ["title"]
      }
    - {label: "Unique ID", name: "ref_id", widget: "shortid", hint: "Automatically generated"}
```
