### ISSUE TITLE
Mock up a Resources page

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/mobility-marketplace#311]
Let's create a preview (via the standard PR process) for what the Resources page will look like.

We'll just go with a fairly bare-bones page for now (no illustrations, no interactive features - just content):

- [x] path should be `/resources`
- [x] title should be `Resources`
- [x] using the standard navbar / footer as other pages
- [x] one paragraph of intro text (lorem ipsum for now)
- [x] sub-sections for e.g. "Getting Started" (lorem ipsum placeholders for 3-4 other sub-section headings for now)
- [x] one or two sentences of explainer text under each sub-section (lorem ipsum for now)
- [x] one or more links under each sub-section (`href="#"` until we have the real files) - maybe a list? or table?

**Comment by thekaveman** [comment]
Use a Jekyll data file (a `.yml` file inside the `_data` directory) to get us set up for eventually auto-populating the site from GCS.

The data file should be oriented as a list (vs. object) to make iteration easier, and include the "sub-section" and the links within that subsection. Something like:

```yaml
- name: Getting Started
  links:
    - https://resources.calitp.org/....
    - https://resources.calitp.org/....

- name: Section Two
  links:
    - https://resources.calitp.org/....
    - https://resources.calitp.org/....

- name: Section Three
  links:
    - https://resources.calitp.org/....
    - https://resources.calitp.org/....
```
